<?php

use Illuminate\Database\Seeder;
use App\Lga;

class LgaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Lga::create(['lga' => 'Abadam', 'state' => 'Borno']);
        Lga::create(['lga' => 'Abaji', 'state' => 'FCT']);
        Lga::create(['lga' => 'Abak', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Abakaliki', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Aba North', 'state' => 'Abia']);
        Lga::create(['lga' => 'Aba South', 'state' => 'Abia']);
        Lga::create(['lga' => 'Abeokuta North', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Abeokuta South', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Abi', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Aboh Mbaise', 'state' => 'Imo']);
        Lga::create(['lga' => 'Abua/Odual', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Adavi', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ado Ekiti', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ado-Odo/Ota', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Afijio', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Afikpo North', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Afikpo South', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Agaie', 'state' => 'Niger']);
        Lga::create(['lga' => 'Agatu', 'state' => 'Benue']);
        Lga::create(['lga' => 'Agwara', 'state' => 'Niger']);
        Lga::create(['lga' => 'Agege', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Aguata', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Ahiazu Mbaise', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ahoada East', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ahoada West', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ajaokuta', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ajeromi-Ifelodu', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Ajingi', 'state' => 'Kano']);
        Lga::create(['lga' => 'Akamkpa', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Akinyele', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Akko', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Akoko-Edo', 'state' => 'Edo']);
        Lga::create(['lga' => 'Akoko North-East', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Akoko North-West', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Akoko South-West', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Akoko South-East', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Akpabuyo', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Akuku-Toru', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Akure North', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Akure South', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Akwanga', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Albasu', 'state' => 'Kano']);
        Lga::create(['lga' => 'Aleiro', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Alimosho', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Alkaleri', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Amuwo-Odofi', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Anambra East', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Anambra West', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Anaocha', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Andoni', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Aninri', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Aniocha North', 'state' => 'Delta']);
        Lga::create(['lga' => 'Aniocha South', 'state' => 'Delta']);
        Lga::create(['lga' => 'Anka', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Ankpa', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Apa', 'state' => 'Benue']);
        Lga::create(['lga' => 'Apapa', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Ado', 'state' => 'Benue']);
        Lga::create(['lga' => 'Ardo Kola', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Arewa Dandi', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Argungu', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Arochukwu', 'state' => 'Abia']);
        Lga::create(['lga' => 'Asa', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Asari-Toru', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Askira/Uba', 'state' => 'Borno']);
        Lga::create(['lga' => 'Atakunmosa East', 'state' => 'Osun']);
        Lga::create(['lga' => 'Atakunmosa West', 'state' => 'Osun']);
        Lga::create(['lga' => 'Atiba', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Atisbo', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Augie', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Auyo', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Awe', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Awgu', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Awka North', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Awka South', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Ayamelum', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Aiyedaade', 'state' => 'Osun']);
        Lga::create(['lga' => 'Aiyedire', 'state' => 'Osun']);
        Lga::create(['lga' => 'Babura', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Badagry', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Bagudo', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Bagwai', 'state' => 'Kano']);
        Lga::create(['lga' => 'Bakassi', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Bokkos', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Bakori', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Bakura', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Balanga', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Bali', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Bama', 'state' => 'Borno']);
        Lga::create(['lga' => 'Bade', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Barkin Ladi', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Barute', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Bassa', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Bassa', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Batagarawa', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Batsari', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Bauchi', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Baure', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Bayo', 'state' => 'Borno']);
        Lga::create(['lga' => 'Bebeji', 'state' => 'Kano']);
        Lga::create(['lga' => 'Bekwarra', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Bende', 'state' => 'Abia']);
        Lga::create(['lga' => 'Biase', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Bichi', 'state' => 'Kano']);
        Lga::create(['lga' => 'Bida', 'state' => 'Niger']);
        Lga::create(['lga' => 'Billiri', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Bindawa', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Binji', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Biriniwa', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Birnin Gwari', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Birnin Kebbi', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Birnin Kudu', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Birnin Magaji/Kiyaw', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Biu', 'state' => 'Borno']);
        Lga::create(['lga' => 'Bodinga', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Bogoro', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Boki', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Boluwaduro', 'state' => 'Osun']);
        Lga::create(['lga' => 'Bomadi', 'state' => 'Delta']);
        Lga::create(['lga' => 'Bonny', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Borgu', 'state' => 'Niger']);
        Lga::create(['lga' => 'Boripe', 'state' => 'Osun']);
        Lga::create(['lga' => 'Bursari', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Bosso', 'state' => 'Niger']);
        Lga::create(['lga' => 'Brass', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Buji', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Bukkuyum', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Buruku', 'state' => 'Benue']);
        Lga::create(['lga' => 'Bungudu', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Bunkure', 'state' => 'Kano']);
        Lga::create(['lga' => 'Bunza', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Burutu', 'state' => 'Delta']);
        Lga::create(['lga' => 'Bwari', 'state' => 'FCT']);
        Lga::create(['lga' => 'Calabar Municipal', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Calabar South', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Chanchaga', 'state' => 'Niger']);
        Lga::create(['lga' => 'Charanchi', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Chibok', 'state' => 'Borno']);
        Lga::create(['lga' => 'Chiku', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Dala', 'state' => 'Kano']);
        Lga::create(['lga' => 'Damaturu', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Damba', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Dambatta', 'state' => 'Kano']);
        Lga::create(['lga' => 'Damboa', 'state' => 'Borno']);
        Lga::create(['lga' => 'Dandi', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Dandume', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Dange Shuni', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Danja', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Dan Musa', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Darazo', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Dass', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Daura', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Dawakin Kudu', 'state' => 'Kano']);
        Lga::create(['lga' => 'Dawakin Tofa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Degema', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Dekina', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Demsa', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Dikwa', 'state' => 'Borno']);
        Lga::create(['lga' => 'Doguwa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Doma', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Donga', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Dukku', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Dunukofia', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Dutse', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Dutsi', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Dutsin Ma', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Eastern Obolo', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ebonyi', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Edati', 'state' => 'Niger']);
        Lga::create(['lga' => 'Ede North', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ede South', 'state' => 'Osun']);
        Lga::create(['lga' => 'Edu', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Ife Central', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ife East', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ife North', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ife South', 'state' => 'Osun']);
        Lga::create(['lga' => 'Efo', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Egbado North', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Egbado South', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Egbeda', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Egbedore', 'state' => 'Osun']);
        Lga::create(['lga' => 'Egor', 'state' => 'Edo']);
        Lga::create(['lga' => 'Ehime Mbano', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ejigbo', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ekeremor', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Eket', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ekiti', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Ekiti East', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ekiti South-West', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ekiti West', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ekwusigo', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Eleme', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Emuoha', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Emure', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Enugu East', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Enugu North', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Enugu South', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Epe', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Esan Central', 'state' => 'Edo']);
        Lga::create(['lga' => 'Esan North-East', 'state' => 'Edo']);
        Lga::create(['lga' => 'Esan South-East', 'state' => 'Edo']);
        Lga::create(['lga' => 'Esan West', 'state' => 'Edo']);
        Lga::create(['lga' => 'Ese Odo', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Esit Eket', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Essien Udim', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Etche', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ethiope East', 'state' => 'Delta']);
        Lga::create(['lga' => 'Ethiope West', 'state' => 'Delta']);
        Lga::create(['lga' => 'Etim Ekpo', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Etina', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Eti Osa', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Etsako Central', 'state' => 'Edo']);
        Lga::create(['lga' => 'Etsako East', 'state' => 'Edo']);
        Lga::create(['lga' => 'Etsako West', 'state' => 'Edo']);
        Lga::create(['lga' => 'Etung', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Ewekoro', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ezeagu', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Ezinihitte', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ezza North', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Ezza South', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Fagge', 'state' => 'Kano']);
        Lga::create(['lga' => 'Fakai', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Faskari', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Fika', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Fufure', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Funakaye', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Fune', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Funtua', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Gabasawa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Gada', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Gagarawa', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Gamawa', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Ganjuwa', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Ganye', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Garki', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Garko', 'state' => 'Kano']);
        Lga::create(['lga' => 'Garun Mallam', 'state' => 'Kano']);
        Lga::create(['lga' => 'Gashaka', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Gassol', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Gaya', 'state' => 'Kano']);
        Lga::create(['lga' => 'Gayuk', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Gezawa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Gbako', 'state' => 'Niger']);
        Lga::create(['lga' => 'Gboko', 'state' => 'Benue']);
        Lga::create(['lga' => 'Gbonyi', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Geidam', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Giade', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Giwa', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Gokana', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Gombe', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Gombi', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Goronyo', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Grie', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Gubio', 'state' => 'Borno']);
        Lga::create(['lga' => 'Gudu', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Gujba', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Gulani', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Guma', 'state' => 'Benue']);
        Lga::create(['lga' => 'Gumel', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Gummi', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Gurara', 'state' => 'Niger']);
        Lga::create(['lga' => 'Guri', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Gusau', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Guzamala', 'state' => 'Borno']);
        Lga::create(['lga' => 'Gwadabawa', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Gwagwalada', 'state' => 'FCT']);
        Lga::create(['lga' => 'Gwale', 'state' => 'Kano']);
        Lga::create(['lga' => 'Gwandu', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Gwaram', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Gwarzo', 'state' => 'Kano']);
        Lga::create(['lga' => 'Gwer East', 'state' => 'Benue']);
        Lga::create(['lga' => 'Gwer West', 'state' => 'Benue']);
        Lga::create(['lga' => 'Gwiwa', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Gwoza', 'state' => 'Borno']);
        Lga::create(['lga' => 'Hadejia', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Hawul', 'state' => 'Borno']);
        Lga::create(['lga' => 'Hong', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Ibadan North', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibadan North-East', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibadan North-West', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibadan South-East', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibadan South-West', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibaji', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ibarapa Central', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibarapa East', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibarapa North', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ibeju-Lekki', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Ibeno', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ibesikpo Asuta', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ibi', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Ibiono-Ibom', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Idah', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Idanre', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Ideato North', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ideato South', 'state' => 'Imo']);
        Lga::create(['lga' => 'Idemili North', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Idemili South', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Ido', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ido Osi', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ifako-Ijaiye', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Ifedayo', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ifedore', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Ifelodu', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Ifelodu', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ifo', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Igabi', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Igalamela Odolu', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Igbo Etiti', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Igbo Eze North', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Igbo Eze South', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Iguebe', 'state' => 'Edo']);
        Lga::create(['lga' => 'Ihiala', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Ihitte/Uboma', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ilaje', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Ijebu East', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ijebu North', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ijebu North East', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ijebu Ode', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ijero', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ijumu', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ika', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ika North East', 'state' => 'Delta']);
        Lga::create(['lga' => 'Ikara', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Ika South', 'state' => 'Delta']);
        Lga::create(['lga' => 'Ikeduru', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ikeja', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Ikenne', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ikere', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ikole', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ikom', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Ikono', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ikorodu', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Ikot Abasi', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ikot Ekpene', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ikpoba Okha', 'state' => 'Edo']);
        Lga::create(['lga' => 'Ikwerre', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ikwo', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Ikwuano', 'state' => 'Abia']);
        Lga::create(['lga' => 'Ila', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ilejemeje', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Ile Oluji/Okeigbo', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Ilesa East', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ilesa West', 'state' => 'Osun']);
        Lga::create(['lga' => 'Illela', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Ilorin East', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Ilorin South', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Ilorin West', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Imeko Afo', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Ingawa', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Ini', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ipokia', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Irele', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Irepo', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Irepodu', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Irepodu', 'state' => 'Osun']);
        Lga::create(['lga' => 'Irepodun/Ifelodu', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Irewole', 'state' => 'Osun']);
        Lga::create(['lga' => 'Isa', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Ise/Oru', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Iseyi', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ishielu', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Isiala Mbano', 'state' => 'Imo']);
        Lga::create(['lga' => 'Isiala Ngwa North', 'state' => 'Abia']);
        Lga::create(['lga' => 'Isiala Ngwa South', 'state' => 'Abia']);
        Lga::create(['lga' => 'Isi', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Isi Uzo', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Isoka', 'state' => 'Osun']);
        Lga::create(['lga' => 'Isoko North', 'state' => 'Delta']);
        Lga::create(['lga' => 'Isoko South', 'state' => 'Delta']);
        Lga::create(['lga' => 'Isu', 'state' => 'Imo']);
        Lga::create(['lga' => 'Isuikwuato', 'state' => 'Abia']);
        Lga::create(['lga' => 'Itas/Gadau', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Itesiwaju', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Itu', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ivo', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Iwajowa', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Iwo', 'state' => 'Osun']);
        Lga::create(['lga' => 'Izzi', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Jaba', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Jada', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Jahu', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Jakusko', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Jalingo', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Jamaare', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Jega', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Jemaa', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Jere', 'state' => 'Borno']);
        Lga::create(['lga' => 'Jibia', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Jos East', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Jos North', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Jos South', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Kabba/Bunu', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Kabo', 'state' => 'Kano']);
        Lga::create(['lga' => 'Kachia', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kaduna North', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kaduna South', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kafin Hausa', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Kafur', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Kaga', 'state' => 'Borno']);
        Lga::create(['lga' => 'Kagarko', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kaiama', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Kaita', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Kajola', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Kajuru', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kala/Balge', 'state' => 'Borno']);
        Lga::create(['lga' => 'Kalgo', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Kaltungo', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Kanam', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Kankara', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Kanke', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Kankia', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Kano Municipal', 'state' => 'Kano']);
        Lga::create(['lga' => 'Karasuwa', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Karaye', 'state' => 'Kano']);
        Lga::create(['lga' => 'Karim Lamido', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Karu', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Katagum', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Katcha', 'state' => 'Niger']);
        Lga::create(['lga' => 'Katsina', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Katsina-Ala', 'state' => 'Benue']);
        Lga::create(['lga' => 'Kaura', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kaura Namoda', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Kauru', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kazaure', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Keana', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Kebbe', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Keffi', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Khana', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Kibiya', 'state' => 'Kano']);
        Lga::create(['lga' => 'Kirfi', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Kiri Kasama', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Kiru', 'state' => 'Kano']);
        Lga::create(['lga' => 'Kiyawa', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Kogi', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Koko/Besse', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Kokona', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Kolokuma/Opokuma', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Konduga', 'state' => 'Borno']);
        Lga::create(['lga' => 'Konshisha', 'state' => 'Benue']);
        Lga::create(['lga' => 'Kontagora', 'state' => 'Niger']);
        Lga::create(['lga' => 'Kosofe', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Kaugama', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Kubau', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kuda', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Kuje', 'state' => 'FCT']);
        Lga::create(['lga' => 'Kukawa', 'state' => 'Borno']);
        Lga::create(['lga' => 'Kumbotso', 'state' => 'Kano']);
        Lga::create(['lga' => 'Kumi', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Kunchi', 'state' => 'Kano']);
        Lga::create(['lga' => 'Kura', 'state' => 'Kano']);
        Lga::create(['lga' => 'Kurfi', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Kusada', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Kwali', 'state' => 'FCT']);
        Lga::create(['lga' => 'Kwande', 'state' => 'Benue']);
        Lga::create(['lga' => 'Kwami', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Kware', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Kwaya Kusar', 'state' => 'Borno']);
        Lga::create(['lga' => 'Lafia', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Lagelu', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Lagos Island', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Lagos Mainland', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Langtang South', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Langtang North', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Lapai', 'state' => 'Niger']);
        Lga::create(['lga' => 'Lamurde', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Lau', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Lavu', 'state' => 'Niger']);
        Lga::create(['lga' => 'Lere', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Logo', 'state' => 'Benue']);
        Lga::create(['lga' => 'Lokoja', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Machina', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Madagali', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Madobi', 'state' => 'Kano']);
        Lga::create(['lga' => 'Mafa', 'state' => 'Borno']);
        Lga::create(['lga' => 'Magama', 'state' => 'Niger']);
        Lga::create(['lga' => 'Magumeri', 'state' => 'Borno']);
        Lga::create(['lga' => 'MaiAdua', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Maiduguri', 'state' => 'Borno']);
        Lga::create(['lga' => 'Maigatari', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Maiha', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Maiyama', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Makarfi', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Makoda', 'state' => 'Kano']);
        Lga::create(['lga' => 'Malam Madori', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Malumfashi', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Mangu', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Mani', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Maradu', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Mariga', 'state' => 'Niger']);
        Lga::create(['lga' => 'Makurdi', 'state' => 'Benue']);
        Lga::create(['lga' => 'Marte', 'state' => 'Borno']);
        Lga::create(['lga' => 'Maru', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Mashegu', 'state' => 'Niger']);
        Lga::create(['lga' => 'Mashi', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Matazu', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Mayo Belwa', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Mbaitoli', 'state' => 'Imo']);
        Lga::create(['lga' => 'Mbo', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Michika', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Miga', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Mikang', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Minjibir', 'state' => 'Kano']);
        Lga::create(['lga' => 'Misau', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Moba', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Mobbar', 'state' => 'Borno']);
        Lga::create(['lga' => 'Mubi North', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Mubi South', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Mokwa', 'state' => 'Niger']);
        Lga::create(['lga' => 'Monguno', 'state' => 'Borno']);
        Lga::create(['lga' => 'Mopa Muro', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Moro', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Moya', 'state' => 'Niger']);
        Lga::create(['lga' => 'Mkpat-Eni', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Municipal Area Council', 'state' => 'FCT']);
        Lga::create(['lga' => 'Musawa', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Mushi', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Nafada', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Nangere', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Nasarawa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Nasarawa', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Nasarawa Ego', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Ndokwa East', 'state' => 'Delta']);
        Lga::create(['lga' => 'Ndokwa West', 'state' => 'Delta']);
        Lga::create(['lga' => 'Nembe', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Ngala', 'state' => 'Borno']);
        Lga::create(['lga' => 'Nganzai', 'state' => 'Borno']);
        Lga::create(['lga' => 'Ngaski', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Ngor Okpala', 'state' => 'Imo']);
        Lga::create(['lga' => 'Nguru', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Ningi', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Njaba', 'state' => 'Imo']);
        Lga::create(['lga' => 'Njikoka', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Nkanu East', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Nkanu West', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Nkwerre', 'state' => 'Imo']);
        Lga::create(['lga' => 'Nnewi North', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Nnewi South', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Nsit-Atai', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Nsit-Ibom', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Nsit-Ubium', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Nsukka', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Numa', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Nwangele', 'state' => 'Imo']);
        Lga::create(['lga' => 'Obafemi Owode', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Obanliku', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Obi', 'state' => 'Benue']);
        Lga::create(['lga' => 'Obi', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Obi Ngwa', 'state' => 'Abia']);
        Lga::create(['lga' => 'Obio/Akpor', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Oboku', 'state' => 'Osun']);
        Lga::create(['lga' => 'Obot Akara', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Obowo', 'state' => 'Imo']);
        Lga::create(['lga' => 'Obubra', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Obudu', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Odeda', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Odigbo', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Odogbolu', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Odo Oti', 'state' => 'Osun']);
        Lga::create(['lga' => 'Odukpani', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Offa', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Ofu', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ogba/Egbema/Ndoni', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ogbadibo', 'state' => 'Benue']);
        Lga::create(['lga' => 'Ogbaru', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Ogbia', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Ogbomosho North', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ogbomosho South', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ogu/Bolo', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ogoja', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Ogo Oluwa', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ogori/Magongo', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ogun Waterside', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Oguta', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ohafia', 'state' => 'Abia']);
        Lga::create(['lga' => 'Ohaji/Egbema', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ohaozara', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Ohaukwu', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Ohimini', 'state' => 'Benue']);
        Lga::create(['lga' => 'Orhionmwo', 'state' => 'Edo']);
        Lga::create(['lga' => 'Oji River', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Ojo', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Oju', 'state' => 'Benue']);
        Lga::create(['lga' => 'Okehi', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Okene', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Oke Ero', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Okigwe', 'state' => 'Imo']);
        Lga::create(['lga' => 'Okitipupa', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Okobo', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Okpe', 'state' => 'Delta']);
        Lga::create(['lga' => 'Okrika', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Olamaboro', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Ola Oluwa', 'state' => 'Osun']);
        Lga::create(['lga' => 'Olorunda', 'state' => 'Osun']);
        Lga::create(['lga' => 'Olorunsogo', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Oluyole', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Omala', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Omuma', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Ona Ara', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Ondo East', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Ondo West', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Onicha', 'state' => 'Ebonyi']);
        Lga::create(['lga' => 'Onitsha North', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Onitsha South', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Onna', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Okpokwu', 'state' => 'Benue']);
        Lga::create(['lga' => 'Opobo/Nkoro', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Oredo', 'state' => 'Edo']);
        Lga::create(['lga' => 'Orelope', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Oriade', 'state' => 'Osun']);
        Lga::create(['lga' => 'Ori Ire', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Orlu', 'state' => 'Imo']);
        Lga::create(['lga' => 'Orolu', 'state' => 'Osun']);
        Lga::create(['lga' => 'Oro', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Orsu', 'state' => 'Imo']);
        Lga::create(['lga' => 'Oru East', 'state' => 'Imo']);
        Lga::create(['lga' => 'Oruk Anam', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Orumba North', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Orumba South', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Oru West', 'state' => 'Imo']);
        Lga::create(['lga' => 'Ose', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Oshimili North', 'state' => 'Delta']);
        Lga::create(['lga' => 'Oshimili South', 'state' => 'Delta']);
        Lga::create(['lga' => 'Oshodi-Isolo', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Osisioma', 'state' => 'Abia']);
        Lga::create(['lga' => 'Osogbo', 'state' => 'Osun']);
        Lga::create(['lga' => 'Oturkpo', 'state' => 'Benue']);
        Lga::create(['lga' => 'Ovia North-East', 'state' => 'Edo']);
        Lga::create(['lga' => 'Ovia South-West', 'state' => 'Edo']);
        Lga::create(['lga' => 'Owan East', 'state' => 'Edo']);
        Lga::create(['lga' => 'Owan West', 'state' => 'Edo']);
        Lga::create(['lga' => 'Owerri Municipal', 'state' => 'Imo']);
        Lga::create(['lga' => 'Owerri North', 'state' => 'Imo']);
        Lga::create(['lga' => 'Owerri West', 'state' => 'Imo']);
        Lga::create(['lga' => 'Owo', 'state' => 'Ondo']);
        Lga::create(['lga' => 'Oye', 'state' => 'Ekiti']);
        Lga::create(['lga' => 'Oyi', 'state' => 'Anambra']);
        Lga::create(['lga' => 'Oyigbo', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Oyo', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Oyo East', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Oyu', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Paikoro', 'state' => 'Niger']);
        Lga::create(['lga' => 'Pankshi', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Patani', 'state' => 'Delta']);
        Lga::create(['lga' => 'Pategi', 'state' => 'Kwara']);
        Lga::create(['lga' => 'Port Harcourt', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Potiskum', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Quaan Pa', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Rabah', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Rafi', 'state' => 'Niger']);
        Lga::create(['lga' => 'Rano', 'state' => 'Kano']);
        Lga::create(['lga' => 'Remo North', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Rijau', 'state' => 'Niger']);
        Lga::create(['lga' => 'Rimi', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Rimin Gado', 'state' => 'Kano']);
        Lga::create(['lga' => 'Ringim', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Riyom', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Rogo', 'state' => 'Kano']);
        Lga::create(['lga' => 'Roni', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Sabon Birni', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Sabon Gari', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Sabuwa', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Safana', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Sagbama', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Sakaba', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Saki East', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Saki West', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Sandamu', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Sanga', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Sapele', 'state' => 'Delta']);
        Lga::create(['lga' => 'Sardauna', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Shagamu', 'state' => 'Ogun']);
        Lga::create(['lga' => 'Shagari', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Shanga', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Shani', 'state' => 'Borno']);
        Lga::create(['lga' => 'Shanono', 'state' => 'Kano']);
        Lga::create(['lga' => 'Shelleng', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Shendam', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Shinkafi', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Shira', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Shiroro', 'state' => 'Niger']);
        Lga::create(['lga' => 'Shongom', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Shomolu', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Silame', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Soba', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Sokoto North', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Sokoto South', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Song', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Southern Ijaw', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Suleja', 'state' => 'Niger']);
        Lga::create(['lga' => 'Sule Tankarkar', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Sumaila', 'state' => 'Kano']);
        Lga::create(['lga' => 'Suru', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Surulere', 'state' => 'Oyo']);
        Lga::create(['lga' => 'Surulere', 'state' => 'Lagos']);
        Lga::create(['lga' => 'Tafa', 'state' => 'Niger']);
        Lga::create(['lga' => 'Tafawa Balewa', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Tai', 'state' => 'Rivers']);
        Lga::create(['lga' => 'Takai', 'state' => 'Kano']);
        Lga::create(['lga' => 'Takum', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Talata Mafara', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Tambuwal', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Tangaza', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Tarauni', 'state' => 'Kano']);
        Lga::create(['lga' => 'Tarka', 'state' => 'Benue']);
        Lga::create(['lga' => 'Tarmuwa', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Taura', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Toungo', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Tofa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Toro', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Toto', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Chafe', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Tsanyawa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Tudun Wada', 'state' => 'Kano']);
        Lga::create(['lga' => 'Tureta', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Udenu', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Udi', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Udu', 'state' => 'Delta']);
        Lga::create(['lga' => 'Udung-Uko', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ughelli North', 'state' => 'Delta']);
        Lga::create(['lga' => 'Ughelli South', 'state' => 'Delta']);
        Lga::create(['lga' => 'Ugwunagbo', 'state' => 'Abia']);
        Lga::create(['lga' => 'Uhunmwonde', 'state' => 'Edo']);
        Lga::create(['lga' => 'Ukanafu', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ukum', 'state' => 'Benue']);
        Lga::create(['lga' => 'Ukwa East', 'state' => 'Abia']);
        Lga::create(['lga' => 'Ukwa West', 'state' => 'Abia']);
        Lga::create(['lga' => 'Ukwuani', 'state' => 'Delta']);
        Lga::create(['lga' => 'Umuahia North', 'state' => 'Abia']);
        Lga::create(['lga' => 'Umuahia South', 'state' => 'Abia']);
        Lga::create(['lga' => 'Umu Nneochi', 'state' => 'Abia']);
        Lga::create(['lga' => 'Ungogo', 'state' => 'Kano']);
        Lga::create(['lga' => 'Unuimo', 'state' => 'Imo']);
        Lga::create(['lga' => 'Urua', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Urue-Offong/Oruko', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Ushongo', 'state' => 'Benue']);
        Lga::create(['lga' => 'Ussa', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Uvwie', 'state' => 'Delta']);
        Lga::create(['lga' => 'Uyo', 'state' => 'Akwa Ibom']);
        Lga::create(['lga' => 'Uzo Uwani', 'state' => 'Enugu']);
        Lga::create(['lga' => 'Vandeikya', 'state' => 'Benue']);
        Lga::create(['lga' => 'Wamako', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Wamba', 'state' => 'Nasarawa']);
        Lga::create(['lga' => 'Warawa', 'state' => 'Kano']);
        Lga::create(['lga' => 'Warji', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Warri North', 'state' => 'Delta']);
        Lga::create(['lga' => 'Warri South', 'state' => 'Delta']);
        Lga::create(['lga' => 'Warri South West', 'state' => 'Delta']);
        Lga::create(['lga' => 'Wasagu/Danko', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Wase', 'state' => 'Plateau']);
        Lga::create(['lga' => 'Wudil', 'state' => 'Kano']);
        Lga::create(['lga' => 'Wukari', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Wurno', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Wushishi', 'state' => 'Niger']);
        Lga::create(['lga' => 'Yabo', 'state' => 'Sokoto']);
        Lga::create(['lga' => 'Yagba East', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Yagba West', 'state' => 'Kogi']);
        Lga::create(['lga' => 'Yakuur', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Yala', 'state' => 'Cross River']);
        Lga::create(['lga' => 'Yamaltu/Deba', 'state' => 'Gombe']);
        Lga::create(['lga' => 'Yankwashi', 'state' => 'Jigawa']);
        Lga::create(['lga' => 'Yauri', 'state' => 'Kebbi']);
        Lga::create(['lga' => 'Yenagoa', 'state' => 'Bayelsa']);
        Lga::create(['lga' => 'Yola North', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Yola South', 'state' => 'Adamawa']);
        Lga::create(['lga' => 'Yorro', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Yunusari', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Yusufari', 'state' => 'Yobe']);
        Lga::create(['lga' => 'Zaki', 'state' => 'Bauchi']);
        Lga::create(['lga' => 'Zango', 'state' => 'Katsina']);
        Lga::create(['lga' => 'Zangon Kataf', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Zaria', 'state' => 'Kaduna']);
        Lga::create(['lga' => 'Zing', 'state' => 'Taraba']);
        Lga::create(['lga' => 'Zurmi', 'state' => 'Zamfara']);
        Lga::create(['lga' => 'Zuru', 'state' => 'Kebbi']);
    }
}
